# Generated by Django 5.0.7 on 2024-08-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=200)),
                ('singer', models.CharField(max_length=50)),
                ('song_type', models.CharField(max_length=50)),
                ('song', models.FileField(upload_to='documents')),
                ('image', models.FileField(upload_to='documents')),
            ],
        ),
    ]
