# Generated by Django 5.0.7 on 2024-08-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_singer_alter_song_singer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='singer',
            field=models.CharField(max_length=100),
        ),
    ]
