# Generated by Django 5.0.7 on 2024-08-07 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_song_singer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singer',
            old_name='singer_name',
            new_name='name',
        ),
    ]
