# Generated by Django 5.0.7 on 2024-08-07 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_rename_singer_name_singer_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Singer',
            new_name='Artist',
        ),
    ]
